test: respect TMPDIR in mktemp (pass --tmpdir)
zlin/wgetpaste pull request #38
Opened 2022-11-22 01:30 UTC by thesamesam

Signed-off-by: Sam James <sam@gentoo.org>

2022-11-22 02:05 UTC, xxc3nsoredxx requested changes

2022-11-22 02:05 UTC, xxc3nsoredxx commented on wgetpaste
> +	[[ -f $TMPF ]] || TMPF=$(mktemp -q -d -tmpdir wgetpaste.XXXXXX)
Ditto, and I think you're missing a `-` in the `--tmpdir`

2022-11-22 02:05 UTC, xxc3nsoredxx commented on test/test.sh
> +# Copyright (C) 2022 Oskari Pirhonen <xxc3ncoredxx@gmail.com>
I'm ok with this, but shouldn't it be "2021-2022" since that's when it was first created?

2022-11-22 03:48 UTC, xxc3nsoredxx commented
lgtm

2022-11-25 18:16 UTC, merged

2022-11-25 18:16 UTC, heirecka commented
Thanks!