Add the quiet flag
zlin/wgetpaste pull request #49
Opened 2023-10-22 20:47 UTC by Richard-Rogalski

Adds a new option that will only return the URL and nothing else to stdout on a successful run. 

This has a few uses:
* Enables piping the output URL into other programs
* Much easier to copy from most term emulators (double click the line, instead of carefully selecting only the link)

I made the --quiet flag only have an affect on a successful run, but if it would make more sense for it to also output nothing on failure, I could do that too.

2023-10-22 21:01 UTC, Richard-Rogalski commented
Oh look, and 
Closes: #19

2023-11-05 04:29 UTC, xxc3nsoredxx requested changes

2023-11-05 04:29 UTC, xxc3nsoredxx commented on wgetpaste
> +	fi
Instead of writing an empty string to `stderr` when `-q`, I'd instead test for not `-q` before writing the "Your paste..." string.

2023-11-05 04:29 UTC, xxc3nsoredxx commented on wgetpaste
> +    -q, --quiet                   stdout only the url
```suggestion
    -q, --quiet                   show the url only
```

2023-11-05 04:29 UTC, xxc3nsoredxx commented on _wgetpaste
> +  '(--quiet -q)'{--quiet,-q}'[stdout only the url]' \
```suggestion
  '(--quiet -q)'{--quiet,-q}'[show the url only]' \
```

2023-11-05 04:48 UTC, xxc3nsoredxx commented
I'd also squash the indentation fix commit.

2023-11-07 03:42 UTC, Richard-Rogalski commented
New unbroke PR: #51

2023-11-07 03:42 UTC, closed without merging